spring:
  data:
    mongodb:
      host: localhost                # MongoDB host
      port: 27017
      database: testdb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1066046816733-m5gmkrniff2m2u9tdat55tg9rof4mlm4.apps.googleusercontent.com
            client-secret: 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
            redirect-uri-template: http://localhost:8080/login/oauth2/code/google
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
